export { default as HomePage } from "./HomePage/HomePage";
export { default as Navibar } from "../components/navbar/navbar";
export { default as Footer } from "../components/navbar/footer";
export { default as LandingPage } from "./LandingPage/LandingPage";
export { default as LoginPage } from "./LoginPage/LoginPage";
export { default as Explore } from "./ExplorePage/ExplorePage";
export { default as RegisterPage } from "./RegisterPage/RegisterPage";
export { default as ForgotPasswordPage } from "./ForgotPasswordPage/ForgotPasswordPage";
export { default as PasswordResetPage } from "./PasswordResetPage/PasswordResetPage";
